---
- hosts: jenkins
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common

    - name: Add Ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Verify Ansible version
      command: ansible --version
